# Generated by Django 5.1.3 on 2024-12-05 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainer.trainer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
